# Generated by Django 4.0.2 on 2022-03-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
