# Generated by Django 4.0.2 on 2022-03-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0004_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authno',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
