# Generated by Django 4.0.2 on 2022-03-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0005_book_authno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authno',
        ),
    ]
