# Generated by Django 4.0.2 on 2022-03-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0007_musician_book_authno_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Musician',
            new_name='Author',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
