# Generated by Django 4.0.2 on 2022-03-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0009_musician_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='publisher',
        ),
    ]
