# Generated by Django 4.0.2 on 2022-03-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0011_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='author',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
