# Generated by Django 4.0.2 on 2022-03-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0014_fruit_remove_author_instrument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
