# Generated by Django 4.0.2 on 2022-03-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('librarymanagement', '0016_remove_book_author_delete_author_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('authno', models.CharField(blank=True, max_length=100)),
                ('cetegory', models.CharField(choices=[('t', 'tech'), ('n', 'non tech')], max_length=1)),
                ('authors', models.ManyToManyField(to='librarymanagement.Author')),
            ],
        ),
    ]
