# Generated by Django 4.0.2 on 2022-03-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0019_publisher_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(blank=True, max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('authno', models.CharField(blank=True, max_length=100)),
                ('cetegory', models.CharField(choices=[('t', 'tech'), ('n', 'non tech')], max_length=1)),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='librarymanagement.publisher')),
                ('authors', models.ManyToManyField(to='librarymanagement.Author')),
            ],
        ),
    ]
