# Generated by Django 4.0.2 on 2022-03-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0021_alter_book_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='publisher',
        ),
    ]
