# Generated by Django 4.0.2 on 2022-03-15 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0022_delete_book_delete_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50, primary_key=b'I01\n', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField()),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('authno', models.CharField(blank=True, max_length=100)),
                ('cetegory', models.CharField(choices=[('t', 'tech'), ('n', 'non tech')], max_length=1)),
                ('authors', models.ManyToManyField(to='librarymanagement.Author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarymanagement.publisher')),
            ],
        ),
    ]
