# Generated by Django 4.0.2 on 2022-03-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0023_publisher_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
