# Generated by Django 4.0.2 on 2022-03-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0024_remove_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_reader',
        ),
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('Book', models.ManyToManyField(to='librarymanagement.Book')),
            ],
        ),
    ]
